mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_servoOutput.org.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_analogInput.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_analogOutput.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_digitalInput.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_digitalOutput.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_lcdOutput.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_serialConfig.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_serialRead.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_serialWrite.c
mex C:\Users\oh\Documents\Spaces\TeamDrive\MATLAB\Targets\mbed\blocks\sfunar_servoOutput.c